version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - '*'
  - package-ecosystem: pip
    directory: /requirements/
    schedule:
      interval: monthly
    ignore:
      - dependency-name: pytest-xprocess
        versions: '>= 1'
    groups:
      python-requirements:
        patterns:
          - '*'
